apiVersion: v1
kind: Secret
metadata:
  name: mysql-user
type: Opaque
data:
  MYSQL_ROOT_USER: cm9vdA==
  MYSQL_ROOT_PASSWORD: TjZnZFZvaUo2YmxYc3BwNw==
  MYSQL_USER: YWdpbGV0Y191c2Vy
  MYSQL_PASSWORD: aVYxZnNnZHNCVHl1TldMWQ==
