apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: agiletc-
commonLabels:
  name: agiletc-mysql
resources:
- cm/mysql-config.yaml
- secrets/mysql-user.yaml
- sts/mysql.yaml
- svc/mysql.yaml
